application: pystream
version: 1
runtime: python
api_version: 1

default_expiration: "3d"

handlers:
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /img
  static_dir: img

- url: /robots.txt
  script: robots.py

- url: /admin/.*
  script: admin.py
  login: admin

- url: .*
  script: public.py
