application: streampy
version: 4
runtime: python
api_version: 1

default_expiration: "1d"

handlers:
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico

- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /robots.txt
  script: robots.py

- url: /cron/stream_check
  script: cron/streams.py
  login: admin

- url: /cron/stats
  script: cron/stats.py
  login: admin

- url: /api/.*
  script: api.py

- url: /admin/.*
  script: admin.py
  login: admin

- url: .*
  script: public.py
